In [24]:
import sys
import ast
from pathlib import Path

In [2]:
import pandas as pd
import altair as alt

In [3]:
this_dir = Path("__file__").parent.absolute()

In [4]:
sys.path.append(str(this_dir.parent / "newshomepages"))

In [5]:
extracts_dir = this_dir.parent / "extracts" / "csv"

In [6]:
analysis_dir = this_dir.parent / "_analysis"

In [75]:
df = pd.read_csv(analysis_dir / "cnn-lighthouse.csv", dtype=str)

In [76]:
def parse_lighthouse(row):
    d = ast.literal_eval(row['summary'])
    row['performance'] = d['performance']
    row['accessibility'] = d['accessibility']
    row['best-practices'] = d['best-practices']
    row['seo'] = d['seo']
    row['pwa'] = d['pwa']
    return row

In [77]:
df = df.apply(parse_lighthouse, axis=1)

In [78]:
trimmed_df = df[[
    'site_handle',
    'file_timestamp',
    'isRepresentativeRun',
    'performance',
    'accessibility',
    'best-practices',
    'seo',
    'pwa',
]]

In [79]:
trimmed_df.head()

,site_handle,file_timestamp,isRepresentativeRun,performance,accessibility,best-practices,seo,pwa
0,cnn,2022-07-23 17:16:31,False,0.15,0.88,0.67,0.84,0.4
1,cnn,2022-07-23 17:16:31,False,0.15,0.88,0.67,0.84,0.4
2,cnn,2022-07-23 17:16:31,True,0.15,0.88,0.67,0.84,0.4
3,cnn,2022-07-23 19:03:49,False,0.15,0.82,0.67,0.77,0.4
4,cnn,2022-07-23 19:03:49,False,0.15,0.82,0.67,0.77,0.4

In [80]:
trimmed_df.describe()

       performance  accessibility  best-practices         seo           pwa
count   252.000000     252.000000      252.000000  252.000000  2.520000e+02
mean      0.126032       0.797619        0.670595    0.792183  4.000000e-01
std       0.040898       0.051918        0.010412    0.033596  5.562162e-17
min       0.000000       0.700000        0.580000    0.770000  4.000000e-01
25%       0.110000       0.780000        0.670000    0.770000  4.000000e-01
50%       0.150000       0.800000        0.670000    0.770000  4.000000e-01
75%       0.150000       0.840000        0.670000    0.840000  4.000000e-01
max       0.150000       0.880000        0.750000    0.850000  4.000000e-01