# Analyze Drudge hyperlinks

In [1]:
import sys
from pathlib import Path

In [11]:
import storysniffer

In [2]:
import numpy as np
import pandas as pd
import altair as alt

In [3]:
this_dir = Path("__file__").parent.absolute()
sys.path.append(this_dir.parent)
sys.path.append(str(this_dir.parent / "newshomepages"))

In [4]:
import altair_theme

In [5]:
alt.themes.register('palewire', altair_theme.theme)
alt.themes.enable('palewire')

ThemeRegistry.enable('palewire')

In [6]:
extracts_dir = this_dir.parent / "extracts" / "csv"

In [7]:
analysis_dir = this_dir.parent / "_analysis"

Read in the sample data

In [8]:
df = pd.read_csv(
    extracts_dir / "drudge-hyperlinks-sample.csv",
    usecols=[
        'handle',
        'file_name',
        'date',
        'text',
        'url',
    ],
    dtype=str,
    parse_dates=["date"]
)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56426 entries, 0 to 56425
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   handle     56426 non-null  object
 1   file_name  56426 non-null  object
 2   date       56426 non-null  datetime64[ns]
 3   text       56182 non-null  object
 4   url        56425 non-null  object
dtypes: datetime64[ns](1), object(4)
memory usage: 2.2+ MB

In [10]:
df.head()

,handle,file_name,date,text,url
0,DRUDGE,drudge-2022-05-21T14:41:56.234274-04:00.hyperl...,2022-05-21,"MUSK BLASTS BIDEN, DEMS OVER 'HATE'...",https://www.cnbc.com/2022/05/20/tesla-boss-elo...
1,DRUDGE,drudge-2022-05-21T14:41:56.234274-04:00.hyperl...,2022-05-21,STOCK -44% FOR YEAR...,https://www.google.com/finance/quote/TSLA:NASD...
2,DRUDGE,drudge-2022-05-21T14:41:56.234274-04:00.hyperl...,2022-05-21,'THERE WILL BE BLOOD'...,https://www.rawstory.com/elon-musk-tesla-stock/
3,DRUDGE,drudge-2022-05-21T14:41:56.234274-04:00.hyperl...,2022-05-21,PRESSURE INTENSIFIES ON WORLD'S RICHEST MAN...,https://www.msn.com/en-us/finance/savingandinv...
4,DRUDGE,drudge-2022-05-21T14:41:56.234274-04:00.hyperl...,2022-05-21,TESLA's golden moment over?,https://unherd.com/thepost/teslas-golden-momen...

Guess links with `storysniffer`

In [12]:
links_df = df.groupby(["text", "url"]).size().rename("n").reset_index()

In [14]:
sniffer = storysniffer.StorySniffer()

/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator CountVectorizer from version 1.1.1 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator FunctionTransformer from version 1.1.1 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator Pipeline from version 1.1.1 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator FeatureUnion from version 1.1.1 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/palewire/.local/share/virtualenvs/news-homepages-Qlfa7zLV/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator GaussianNB from version 1.1.1 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [13]:
links_df

,text,url,n
0,\nWildfire near Yosemite National Park explode...,https://apnews.com/article/wildfires-fires-cal...,3
1,Committee Kicks Off Capitol Attack Public Pro...,https://apnews.com/article/capitol-siege-ivank...,1
2,DeSantis calls out the Chinese Communist Part...,https://www.dailymail.co.uk/news/article-11042...,3
3,Documentary: The Don called the rioters 'sma...,https://variety.com/2022/tv/news/unprecedented...,1
4,Hearing Delivers Political Blow That His Riva...,https://kdhnews.com/news/politics/explosive-ja...,5
...,...,...,...
6774,[UK] INDEPENDENT,http://www.independent.co.uk/,232
6775,[UK] METRO,https://metro.co.uk/,232
6776,[UK] SUN,http://www.thesun.co.uk,232
6777,[UK] TELEGRAPH,http://www.telegraph.co.uk/,232
6778,privacy policy.,/privacy/,43