# Analyze Drudge hyperlinks

In [1]:
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

In [2]:
import storysniffer

In [3]:
import numpy as np
import pandas as pd
import altair as alt

In [4]:
this_dir = Path("__file__").parent.absolute()
sys.path.append(this_dir.parent)
sys.path.append(str(this_dir.parent / "newshomepages"))

In [5]:
import altair_theme

In [6]:
alt.themes.register('palewire', altair_theme.theme)
alt.themes.enable('palewire')

ThemeRegistry.enable('palewire')

In [7]:
extracts_dir = this_dir.parent / "extracts" / "csv"

In [8]:
analysis_dir = this_dir.parent / "_analysis"

Read in the sample data

In [9]:
df = pd.read_csv(
    extracts_dir / "drudge-hyperlinks-sample.csv",
    usecols=[
        'handle',
        'file_name',
        'date',
        'text',
        'url',
    ],
    dtype=str,
    parse_dates=["date"]
)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61755 entries, 0 to 61754
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   handle     61755 non-null  object
 1   file_name  61755 non-null  object
 2   date       61755 non-null  datetime64[ns]
 3   text       61489 non-null  object
 4   url        61754 non-null  object
dtypes: datetime64[ns](1), object(4)
memory usage: 2.4+ MB

In [11]:
df.head()

,handle,file_name,date,text,url
0,DRUDGE,drudge-2022-05-31T14:43:07.863919-04:00.hyperl...,2022-05-31,Kremlin propaganda declares 'WW3 has started'...,https://www.dailystar.co.uk/news/world-news/ru...
1,DRUDGE,drudge-2022-05-31T14:43:07.863919-04:00.hyperl...,2022-05-31,Threatens to wipe out USA with just four Satan...,https://www.the-sun.com/news/5460070/russia-th...
2,DRUDGE,drudge-2022-05-31T14:43:07.863919-04:00.hyperl...,2022-05-31,Moscow Military Brass Caught Venting: 'You're ...,https://www.thedailybeast.com/top-russian-mili...
3,DRUDGE,drudge-2022-05-31T14:43:07.863919-04:00.hyperl...,2022-05-31,Zelensky warns of famine risk from blockade of...,https://thehill.com/policy/international/russi...
4,DRUDGE,drudge-2022-05-31T14:43:07.863919-04:00.hyperl...,2022-05-31,Cracks Show in Western Front...,https://www.wsj.com/articles/cracks-appear-in-...

Guess links with `storysniffer`

In [12]:
links_df = df.groupby(["text", "url"]).size().rename("n").reset_index()

In [13]:
sniffer = storysniffer.StorySniffer()

In [14]:
links_df.describe()

                 n
count  7103.000000
mean      8.656624
std      39.302088
min       1.000000
25%       1.000000
50%       2.000000
75%       3.000000
max     254.000000

In [15]:
links_df['is_story'] = links_df.apply(lambda x: sniffer.guess(x['url'], text=x['text']), axis=1)

In [16]:
links_df.is_story.value_counts()

True     6835
False     268
Name: is_story, dtype: int64

In [17]:
links_df.is_story.value_counts(normalize=True)

True     0.962269
False    0.037731
Name: is_story, dtype: float64

In [18]:
links_df.to_csv("./drudge-hyperlinks-storysniffer-guesses.csv", index=False)

Make some manual fixes

In [19]:
blacklist = [
    "/privacy/",
]

In [20]:
links_df.loc[
    links_df.url.isin(blacklist),
    'is_story'
] = False

In [21]:
substack_pattern = ".(substack|theankler|commonsense).(com|news)/p/"

In [22]:
links_df.loc[
    links_df.url.str.contains(substack_pattern),
    'is_story'
] = True

/tmp/ipykernel_1839511/673093257.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  links_df.url.str.contains(substack_pattern),

In [23]:
time_pattern = "^https://time.com/\d{5,}/*"

In [24]:
links_df.loc[
    links_df.url.str.contains(time_pattern),
    'is_story'
] = True

In [25]:
studyfinds_pattern = "^https://www.studyfinds.org/*.{5,}"

In [26]:
links_df.loc[
    links_df.url.str.contains(studyfinds_pattern),
    'is_story'
] = True

In [27]:
bbc_pattern = "^https://www.bbc.com/news/*.{5,}"

In [28]:
links_df.loc[
    links_df.url.str.contains(bbc_pattern),
    'is_story'
] = True

In [29]:
jpost_pattern = "^https://www.jpost.com/breaking-news/*.{5,}"

In [30]:
links_df.loc[
    links_df.url.str.contains(jpost_pattern),
    'is_story'
] = True

In [31]:
braint_pattern = "^https://www.braintomorrow.com/*.{5,}"

In [32]:
links_df.loc[
    links_df.url.str.contains(braint_pattern),
    'is_story'
] = True

Knock out anything that appears most of the time

In [33]:
n = len(df.file_name.unique())

In [42]:
links_df.loc[
    links_df.n >= n * .5,
    'is_story',
] = False

In [43]:
links_df.to_csv("./drudge-hyperlinks-storysniffer-tweaks.csv", index=False)

In [44]:
links_df[
    (links_df.n < 40) &
    (links_df.is_story == False)
].sort_values("url").head(5)

,text,url,n,is_story,domain
3468,LIVE HEAT MAP...,http://hp2.wright-weather.com/icons/us_heat.gif,8,False,hp2.wright-weather.com
3473,LIVE: TEMP MAP,http://hp2.wright-weather.com/icons/us_heat.gif,2,False,hp2.wright-weather.com
3474,LIVE: TEMP MAP...,http://hp2.wright-weather.com/icons/us_heat.gif,14,False,hp2.wright-weather.com
4505,PARTICIPANTS...,https://bilderbergmeetings.org/press/press-rel...,1,False,bilderbergmeetings.org
1691,DEPP JUSTICE!,https://deadline.com/tag/depp-heard-trial/,1,False,deadline.com

Tally domains

In [45]:
links_df['domain'] = links_df.url.apply(lambda x: urlparse(x).netloc)

In [46]:
links_df[links_df.is_story].domain.value_counts().reset_index().head(10)

                 index  domain
0          www.msn.com     810
1           apnews.com     503
2          www.wsj.com     377
3       news.yahoo.com     323
4            dnyuz.com     301
5  www.dailymail.co.uk     295
6         www.cnbc.com     219
7      www.the-sun.com     217
8          www.cnn.com     210
9           nypost.com     202

In [53]:
story_df = links_df[links_df.is_story].copy()

In [81]:
def is_trump(text):
    token_list = [t.lower() for t in text.split()]
    if 'trump' in token_list:
        return True
    elif 'donald' in token_list:
        return True
    elif 'don' in token_list:
        return True
    else:
        return False

In [82]:
story_df['is_trump'] = story_df.text.apply(is_trump)

In [83]:
story_df.is_trump.value_counts()

False    6678
True      178
Name: is_trump, dtype: int64

In [84]:
trump_df = story_df[story_df.is_trump].copy()

In [85]:
date_df = df[['url', 'date']].sort_values(["url", "date"], ascending=[True, True]).drop_duplicates("url", keep="first")

In [86]:
trump_df = trump_df.merge(date_df, on="url").sort_values("date", ascending=True)

In [89]:
trump_df.tail()

,text,url,n,is_story,domain,is_trump,date
69,NY AG's investigation into Trump nears endgame...,https://www.vanityfair.com/news/2022/08/letiti...,1,True,www.vanityfair.com,True,2022-08-26
68,NY AG probe into Trump nears endgame...,https://www.vanityfair.com/news/2022/08/letiti...,3,True,www.vanityfair.com,True,2022-08-26
114,The Don Rages At FBI 'Hacks and Thugs'...,https://www.mediaite.com/trump/trump-attacks-d...,6,True,www.mediaite.com,True,2022-08-26
82,"Of all legal threats, is this one that could t...",https://www.theguardian.com/us-news/2022/aug/2...,5,True,www.theguardian.com,True,2022-08-27
28,Don Jr. Posts Meme About His Fathers Crotch...,https://www.thedailybeast.com/donald-trump-jr-...,5,True,www.thedailybeast.com,True,2022-08-27

In [88]:
list(trump_df.text.unique())

['Herschel Walker Accuses Trump of Lying About Convincing Him to Run...',
 "'Outsider' in NV Senate primary surges, rattling Trump pick...",
 "Republicans who texted Meadows say The Don could've stopped violence...",
 'Trump election probe grand jury to hear from Raffensperger...',
 'Former Trump aide Peter Navarro indicted for contempt of Congress...',
 'Trump Summer Plans Include 7-Hour Grilling in Fraud Suit...',
 'The Don weighs big bet in Alabama Senate race...',
 "Trump call to 'walk down to Capitol' prompted Secret Service scramble...",
 "TRUMP ISSUES STATEMENT:  'DRUDGE IS DEAD'...",
 'Biden Trashes Trump On Kimmel...',
 'Will Put The Don at Center of Plot...',
 'NYPOST:  Republicans should leave Trump -- and obsessed Dems -- behind...',
 'The Don Throws Her Under the Bus...',
 "Trump at Center of 'Attempted Coup'...",
 "Mo Brooks Lashes Out at 'Conned' Trump After Rival Gets Endorsement...",
 "NO MORE IN '24:  GERGEN SAYS BIDEN, TRUMP TOO OLD...",
 "Panel hears: Trump 'detached from reality' in defeat...",
 "Do Dems Already Have Their Own Trump That Could Win in '24?",
 "Panel to Make Case The Don Put Pence Life 'in Danger'...",
 "Trump lawyer cited 'heated fight' among justices...",
 'NOONAN: Trump Voters Need New Direction...',
 "NOONAN: Trump Voters Need New Direction...\nHe's sure loser in '24...",
 'Trump ridicules Pence at evangelical conference...',
 'NYT:  Despite Growing Evidence, Prosecution of Trump Would Face Challenges...',
 'POLL:  6 in 10 Americans say Trump should be charged for Jan. 6...',
 'POLL:  6 in 10 say Trump should be charged for inciting Jan. 6...',
 'POLL:  6 in 10 say Trump should be charged for inciting insurrection...',
 "Watergate prosecutor: Georgia case could 'send Trump to prison'...",
 'The Don asked if he expects to be taken out in shackles!',
 "The Don asked if he expects to be taken out 'in shackles'...",
 "Watergate prosecutor: Georgia case could 'send Donald to prison'...",
 'Can DeSantis Displace Trump as Combatant-in-Chief?',
 'Cheney Paying Price for Crossing The Don in Her Home State...',
 'Alabama Senate race tests Trump sway after endorsement flip-flop...',
 'Trump ratchets up attacks amid questions about viability...',
 'State officials detail pressure campaign to keep Trump in office...',
 'Increasingly abandoned and isolated, will Trump burn it all down?',
 'Increasingly abandoned and isolated, will Don burn it all down?',
 'Trump seething over McCarthy...',
 'Doc Maker Claims Trump Had Secret Call With Putin Just Before Election...',
 "NYT: Trump Publicly Credits God for Decision Privately Calls 'Bad'...",
 "Trump Publicly Credits God -- Privately Says 'Bad'...",
 "Lawmaker calls ruling 'victory for white life' as Trump rally cheers...",
 "Filmmaker Claims:  Eric Trump Thought Violence After Election 'Fair Game'...",
 'Jan 6 committee focuses on phone calls among Trump children and aides...',
 'Committee focuses on phone calls among Trump children and aides...',
 'WASHINGTON EXAMINER: TRUMP IS A DISGRACE; SHOULD NEVER BE SUPPORTED AGAIN...',
 'WASHINGTON EXAMINER: THE DON IS A DISGRACE; SHOULD NEVER BE SUPPORTED AGAIN...',
 'Filmmaker Alex Holder says Trump lost mind after Jan 6...',
 'Filmmaker Alex Holder says Trump lost his mind after January 6...',
 'Filmmaker Alex Holder says Trump lost his mind after Jan 6...',
 "The Don derides Cassidy Hutchinson as 'this girl'...",
 'Trump Eyes Early Announcement...',
 'NYT: Trump Eyes Early Announcement...',
 'NYT: Trump Eyes Early 2024 Announcement as Capitol Riot Scrutiny Intensifies...',
 'NYT: The Don Eyes Early Announcement as Capitol Riot Scrutiny Intensifies...',
 'Oz strategy for winning PA: Trump who?',
 "Oz's strategy for winning PA: Trump who?",
 "Liz Cheney warns GOP 'can't survive' if The Don becomes nominee...",
 "Cheney warns GOP 'can't survive' if The Don nominee...",
 "SCORN ON THE 4TH OF JULY...\nTRUMP CALLS CHENEY 'DESPICABLE HUMAN BEING'...",
 'New Jan. 6 Trump documentary footage revealed...',
 'GA grand jury subpoenas Giuliani, Graham, Trump confidantes...',
 'Turns to Direct Attacks on Trump as Midterms Near...',
 'THE DON SHOWS OFF NEW 757...',
 'KURTZ:  Media turning against both Trump AND Biden...',
 'Congress seeks probe after IRS targeted Trump enemies with audits...',
 'Johnson faced revolt in his party. Trump never had that problem... ',
 "Cowded Republican field could help The Don in '24?",
 'Trump lawyer interviewed with FBI about case...',
 'WI County That Heavily Backed Trump Has Lots of DeSantis Fans...',
 " Documentary:  The Don called the rioters 'smart'... ",
 "Documentary:  The Don called rioters 'smart'... ",
 'POLL: HALF REPUBLICANS  ABANDON DON',
 'Trump rally canceled as former president summoned to court... Developing...',
 'POLL: HALF REPUBLICAN VOTERS ABANDON TRUMP',
 "Jan. 6 panel probes Trump 'siren call' to extremists...",
 'Trump rally canceled as former president summoned to court...',
 "The Don Fires Back at Elon!\nSays He'd Be 'Worthless' without Govt Subsidies, Bashes TESLA Cars...",
 "Social went easy on Trump because it 'relished' the power, ex-employee claims...",
 "Social went easy on Trump because it 'relished' power, ex-employee claims...",
 'UPDATE: Jan. 6 Witness Trump Tried to Call Revealed...',
 'Trump looks to fall launch for 2024, potentially upending midterms...',
 'UPDATE: Jan. 6 Witness The Don Tried to Call Revealed...',
 'UPDATE:  Witness The Don Tried to Call Revealed...',
 'The Don Fundraises in Email About Passing?',
 'Trump Allies Line Up Shadow Govt...',
 'IVANA TRUMP DEAD...',
 'TRUMP FUNDRAISING TRAILS DESANTIS...',
 'Trump slammed for hosting Saudi golf events...',
 "The Don Sides With SAUDI Golf Tour Over 'Disloyal' PGA...",
 'ROGAN CALLS TRUMP MAN BABY; SAYS WAS ON DRUGS IN WHITE HOUSE...',
 'Trump looms large over Biden decision...',
 'FOX Posts Montage of Trump Voters Jumping For DeSantis...',
 "2024: McConnell says The Don will face 'crowded' field...",
 'Blooper Reel of The Don Struggling to Condemn Rioters...',
 "Wisconsin House speaker says Trump called him to overturn '20 election -- 20 months later...",
 "WI House speaker says Trump called him to overturn '20 election -- 20 months later...",
 "Inside Trump '25: Radical plan for second term...",
 'After gripping Capitol riot hearings -- will Trump be indicted?',
 'Will Trump be indicted?',
 'NYPOST:  THE DON UNWORTHY...',
 'Trump making few inroads outside MAGA loyalists...',
 'The Don tests waning appeal in trip to DC...',
 'Deepens probe of Trump Cabinet...',
 "Biden slams Trump for inaction over 'medieval hell' of Capitol riot... ",
 "Trump Says LIV Golf Has Been Worth 'Billions of Dollars' in Publicity for Kingdom...",
 'Trump hosting Saudi-backed golf tournament...',
 'When Trump Declares He Loses Control of $103 Million...',
 'Don and Ron Jockey for Position Ahead of Potential 2024 Showdown...',
 'GARLAND OPEN TO PROSECUTING TRUMP',
 'GEORGIA DANGER FOR DON',
 'TRUMP TO SUE CNN...',
 'Now on the tee for LIV Golf: Trump National and polarizing former president...',
 'ROVE: Where Do Trump Donations Go?',
 'Trump uses presidential seal at Saudi golf tournament...',
 'Trump accused of burying Ivana at golf club for TAX BREAK...',
 'The Don buried Ivana at club for tax break?',
 'MAG: Trump Lawyers Preparing Legal Defenses Against Criminal Charges...',
 'MCCARTHY: Signal DOJ Weighing Trump Indictment...',
 'MCCARTHY:  Justice IS Weighing Trump Indictment...',
 'HOLDER: TRUMP LIKELY TO BE CRIMINALLY CHARGED...',
 "Cheney Downloads on Trump in Campaign Ad for Daughter...\n'Never been individual who is greater threat to republic'...",
 "Cheney Downloads on Trump in Ad for Daughter...\n'Never been individual who is greater threat to republic'...",
 "The Don fundraising off 'upcoming' lawsuit Against CNN...",
 "The Don fundraising off 'upcoming' suit against CNN...",
 'TRUMP DUMP: SHREDDED DOCS IN TOILETS...\nMULTIPLE INCIDENTS...',
 'MORE HEAT ON THE DON',
 'Kerik Predicts Trump Assassination...',
 "'SOUTH PARK' creators details Trump movie they couldn't get made...",
 'FBI RAIDS TRUMP',
 'The Don Under Intense Legal Scrutiny...',
 "TRUMP FEARS AGENTS 'PLANTED STUFF'\n9 HOUR SEARCH",
 'REPORT:  Informer Revealed What Trump Docs Were Hidden, Where...',
 'THE DON PLEADS FIFTH',
 'Trump Signed Law Stiffening Penalty For Mishandling Classified Info to FIVE YEARS Prison...',
 'Tax fraud trial of Trump Org, CFO set for October...',
 'Ex-CIA chief endorses executing leakers of nuclear secrets after Trump raid bombshell...',
 'Ex-CIA chief endorses executing leakers of secrets after Trump raid bombshell...',
 'The Don Sics Republicans on FBI...',
 'DON SENDS CRYPTIC MESSAGE TO AG',
 'Trump Lawyer Told DOJ Classified Material Had Already Been Returned...',
 'Trump Lawyer Told Justice Dept. That Classified Material Had Been Returned...',
 'LAWMAKERS CALL FOR TRUMP SECURITY THREAT ASSESSMENT...',
 "Kari Lake Wants You to Know She Thinks Trump and DeSantis Have 'BDE'...",
 "Trump warns 'terrible things going to happen'...",
 'Georgia election data copied under direction of Trump attorney...',
 'Trump Org Weisselberg expected to plead guilty in tax avoidance scheme...',
 'The Don pushing theory attack on FBI in OH was false flag...',
 "Trump warns 'terrible things are going to happen'...",
 'The Don pushing theory Ohio attack was false flag...',
 "Trump rushing to hire seasoned lawyers. But keeps hearing 'No'...",
 "Trump rushing to hire seasoned lawyers. But he keeps hearing 'No'...",
 'CHENEY RELOADS ON TRUMP MOB',
 'Plea Deal Requires Weisselberg to Testify at Trump Org Trial...',
 'Trump CFO wiill admit to 15 felonies!',
 'LABASH:  Chronic Trump Fatigue...',
 "LABASH:  Chronic Trump Fatigue...\nWhen You're Too Exhausted To Be Outraged...",
 'Trump CFO admits to 15 felonies... Developing...',
 "'We got rolled': How conservative grassroots lost because focused on Trump Show...",
 'The Don sues to block DOJ from reviewing seized materials...',
 "DON JR ADMITS?\n'WOULD BE GOOD' IF NUKE CODES AT MAR-A-LAGO",
 'Trump Had More Than 700 Classified Documents Hidden In Florida... Developing...',
 'NYT:  Trump Had More Than 300 Classified Documents Hidden In Florida... Developing...',
 "Political analyst loses job after calling Trump 'orange'...",
 'POLL:  Ron Flattens Don By 15 Points in 3-Way Race...',
 'FBI POUNCED AFTER DON OBSTRUCTED FOR MONTHS...',
 "Without Presidency's Protections, Trump Struggles for Strategy...",
 "New Dem star calls Trump 'Traitorous'...\n'If I Had Done What He Did, I Would've Been in Jail'...",
 "NY AG's investigation into Trump nears endgame...",
 'NY AG probe into Trump nears endgame...',
 "The Don Rages At FBI 'Hacks and Thugs'...",
 'Of all legal threats, is this one that could take Trump down?',
 'Don Jr. Posts Meme About His Fathers Crotch...']